server:
  port: 8762
# spring的配置文件
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaokuankuan/springcloud/        #配置git仓库地址
          search-paths: resp                                     #配置仓库路径
          username: 935068797@qq.com                              #访问git仓库的账号
          password: ********                                      #访问git仓库的密码
          label: master                                             #git仓库的分支
